### ISSUE TITLE
Ability to cross out goals in lockout mode

### ISSUE THREAD

**Issue by t-vaudry** [nt5664/HPBingoCounter#1]
When counting for lockout, after someone else claims a goal, it would be nice to be able to cross out goals so we don't continue to count for nothing.

![image](https://github.com/user-attachments/assets/e6c20ff3-d6d2-46a9-88ec-3cd3785664de)

Either a big X or dark color shading. Using an X in the corner to close off the goal, and reuse to unset it.

**Comment by nt5664** [comment]
Thank you for the feedback, the feature is now implemented and released in v2.2
